- id: sqlfluff-lint
  name: sqlfluff-lint
  entry: sqlfluff lint
  language: python
  description: 'Lints sql files with `sqlfluff`'
  types: [sql]
  require_serial: true
  additional_dependencies: []

- id: sqlfluff-fix
  name: sqlfluff-fix
  entry: sqlfluff fix
  language: python
  description: 'Fixes sql lint errors with `sqlfluff`'
  types: [sql]
  require_serial: true
  additional_dependencies: []
